* Refactoring
** DONE replace default hook modifier in manager.scm with setter functions
default record setter should be private, another public one should be created to customize the behavior. It's also a good idea to call all hooks needed in setters rather than relying on user to run them. Add an optional parameter to disable hook call.
** TODO move all extra modules to ~contrib~
including ~window-rules~ and any other module that seems like a plugin
** TODO create a hash-table for all ~contrib~ and extra configuration variables
gaps parameters, mode, message-timeout and all other manager state variables should move to the hash-table which is the only variable referenced by the ~manager~ other than the list of outputs, seats, and windows.

** TODO document hooks
currently it's not clear what the parameters are, should probably be documented in ~hooks.scm~

** TODO add metadata to outputs, workspaces, containers, and windows
this will allow modules to add their metadata to types so they can persist and be shared across other modules. Should be very similar to how manager handles configuration.

** TODO plan animations
no need for implementation now, but common functions should be used and expect animations to be introduced later. There should be no call changes to introduce animations.

** TODO maybe improve automatic layout
the implementation used to check for specific events like window creation and apply only needed changes to the layout. It's much easier to just reload the whole layout on some specific events needed by the layout. Check performance difference and change the logic accordingly. If there is no huge impact in performance keep current approach because it's much easier to read and maintain.

** TODO make default layout manual

** TODO check out dirty manager sequences and imperfect frames
